-- 코드를 입력하세요
SELECT
    FO.PRODUCT_ID,
    FP.PRODUCT_NAME,
    SUM(FO.AMOUNT) * FP.PRICE AS TOTAL_SALES
FROM FOOD_ORDER AS FO
JOIN FOOD_PRODUCT AS FP ON
    FP.PRODUCT_ID = FO.PRODUCT_ID AND
    MONTH(FO.PRODUCE_DATE) = 5
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID ASC