-- 코드를 입력하세요
SELECT
    SUB.CATEGORY,
    SUB.MAX_PRICE,
    FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP,
    (
        SELECT
            CATEGORY,
            MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
        GROUP BY CATEGORY
    ) AS SUB
WHERE SUB.CATEGORY = FP.CATEGORY AND SUB.MAX_PRICE = FP.PRICE
ORDER BY SUB.MAX_PRICE DESC