-- 코드를 입력하세요
SELECT
    RH.HISTORY_ID,
    ROUND(C.DAILY_FEE * (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1) * (100 - MAX(IFNULL(DP.DISCOUNT_RATE, 0))) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
JOIN CAR_RENTAL_COMPANY_CAR AS C ON RH.CAR_ID = C.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP ON
    DP.CAR_TYPE LIKE C.CAR_TYPE AND
    CAST(REGEXP_SUBSTR(DP.DURATION_TYPE, "[0-9]+") AS UNSIGNED) <= DATEDIFF(RH.END_DATE, RH.START_DATE) + 1
WHERE C.CAR_TYPE LIKE "트럭"
GROUP BY RH.HISTORY_ID
ORDER BY FEE DESC, RH.HISTORY_ID DESC;